language: c
sudo: false
branches:
only:
  - master
os:
  - linux
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes psutil yaml pyyaml
  - conda-env create -f gds_stack.yml

script: 
  - source activate gsa2019
    #- jupyter nbconvert --to markdown --execute --ExecutePreprocessor.timeout=480 --allow-errors check_gds_stack.ipynb --stdout
    # - jupyter nbconvert --to markdown --execute --ExecutePreprocessor.timeout=480 check_gds_stack.ipynb
    #- conda list --explicit
    #- source activate gds_fixed
    #- jupyter nbconvert --to markdown --execute --ExecutePreprocessor.timeout=480 check_gds_stack.ipynb

notifications:
    email:
        recipients:
            - jreades@gmail.com
        on_failure: always


