rancher:
  ssh:
    keys:
      dsa: |+
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABsQAAAAdzc2gtZH
        NzAAAAgQD5X9evycSWnH+JO9YtZau7ckjmy8QPEiO5WZosbNBUURXsy2w+5ssp4XHlz5UF
        tnjg+fKCTYyRYZliT6nOpEsDfXW1zK+Ftf/XhSmc1TEz6B767aONdYBig1rOKSybcEHU4B
        7nythjZ/FzdWtIgFjvVn3dJ4rjyWRke3lxOkH27QAAABUA4+iWVHQ/2q/MsHV1QSvs2sXF
        ASsAAACAcvV+tHbnOofdyORl+ZEnqpRDLN/0fq6BMMfQ6z7zA5MWAQm8GGP30pkFAabAS6
        jy1KjhmxYhOJOo/iXOjoLw+9HXdRbzzOdJHp3pIfJ4sSSacy2/qmXPxmw1tB4JDcIYgOsT
        E+ld9k52VHqP+YTxnsjPeXliDs/GucVtp9biUGcAAACABSbKxxlo80o0aCm7PbZAiKf20o
        oQUhg9UUW6DOD6+io5udP9dZ99n5rgDKbEoYMADpJNq63TI3bXINDP8m/itXt9bxKKv8mp
        LCnI8gQ8VtVyFOJk0td0+nLR/S3Z7opl+ALI5M8VMyBDu33xe9YCLC01D1vQvXLPT/sIe3
        HvGSIAAAHoBfOK8AXzivAAAAAHc3NoLWRzcwAAAIEA+V/Xr8nElpx/iTvWLWWru3JI5svE
        DxIjuVmaLGzQVFEV7MtsPubLKeFx5c+VBbZ44Pnygk2MkWGZYk+pzqRLA311tcyvhbX/14
        UpnNUxM+ge+u2jjXWAYoNaziksm3BB1OAe58rYY2fxc3VrSIBY71Z93SeK48lkZHt5cTpB
        9u0AAAAVAOPollR0P9qvzLB1dUEr7NrFxQErAAAAgHL1frR25zqH3cjkZfmRJ6qUQyzf9H
        6ugTDH0Os+8wOTFgEJvBhj99KZBQGmwEuo8tSo4ZsWITiTqP4lzo6C8PvR13UW88znSR6d
        6SHyeLEkmnMtv6plz8ZsNbQeCQ3CGIDrExPpXfZOdlR6j/mE8Z7Iz3l5Yg7PxrnFbafW4l
        BnAAAAgAUmyscZaPNKNGgpuz22QIin9tKKEFIYPVFFugzg+voqObnT/XWffZ+a4AymxKGD
        AA6STaut0yN21yDQz/Jv4rV7fW8Sir/JqSwpyPIEPFbVchTiZNLXdPpy0f0t2e6KZfgCyO
        TPFTMgQ7t98XvWAiwtNQ9b0L1yz0/7CHtx7xkiAAAAFD7VRe3wnaetZ/wP5fIQvP0sI/2y
        AAAADHJvb3RAcmFuY2hlcgECAwQFBgc=
        -----END OPENSSH PRIVATE KEY-----
      dsa-pub: |+
        ssh-dss AAAAB3NzaC1kc3MAAACBAPlf16/JxJacf4k71i1lq7tySObLxA8SI7lZmixs0FRRFezLbD7myynhceXPlQW2eOD58oJNjJFhmWJPqc6kSwN9dbXMr4W1/9eFKZzVMTPoHvrto411gGKDWs4pLJtwQdTgHufK2GNn8XN1a0iAWO9Wfd0niuPJZGR7eXE6QfbtAAAAFQDj6JZUdD/ar8ywdXVBK+zaxcUBKwAAAIBy9X60duc6h93I5GX5kSeqlEMs3/R+roEwx9DrPvMDkxYBCbwYY/fSmQUBpsBLqPLUqOGbFiE4k6j+Jc6OgvD70dd1FvPM50kenekh8nixJJpzLb+qZc/GbDW0HgkNwhiA6xMT6V32TnZUeo/5hPGeyM95eWIOz8a5xW2n1uJQZwAAAIAFJsrHGWjzSjRoKbs9tkCIp/bSihBSGD1RRboM4Pr6Kjm50/11n32fmuAMpsShgwAOkk2rrdMjdtcg0M/yb+K1e31vEoq/yaksKcjyBDxW1XIU4mTS13T6ctH9LdnuimX4AsjkzxUzIEO7ffF71gIsLTUPW9C9cs9P+wh7ce8ZIg== root@rancher
      ecdsa: |+
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
        1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQRvbEyYhuvk86SZaNKKsBUtWmeDqUbj
        pCwanJ4ErtjC7FFQXEhTTyK1hYmcLR3zJKGPS/mzalg22ixjZ81tQMQDAAAAqI+OO1+Pjj
        tfAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG9sTJiG6+TzpJlo
        0oqwFS1aZ4OpRuOkLBqcngSu2MLsUVBcSFNPIrWFiZwtHfMkoY9L+bNqWDbaLGNnzW1AxA
        MAAAAgGEjHAwWeDG9WPhgVVG/LVvnmQtTxokZh1G7ZNiVJqFgAAAAMcm9vdEByYW5jaGVy
        AQIDBA==
        -----END OPENSSH PRIVATE KEY-----
      ecdsa-pub: |+
        ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG9sTJiG6+TzpJlo0oqwFS1aZ4OpRuOkLBqcngSu2MLsUVBcSFNPIrWFiZwtHfMkoY9L+bNqWDbaLGNnzW1AxAM= root@rancher
      ed25519: |+
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACCVxLIAaY1DxzSS4wTVpdIOuucB179vB/mnnjX1oy/q9wAAAJAVLspiFS7K
        YgAAAAtzc2gtZWQyNTUxOQAAACCVxLIAaY1DxzSS4wTVpdIOuucB179vB/mnnjX1oy/q9w
        AAAED1RKeaJURlG0R0AyJUK25yvqwmcjvyIIpW0CC9opY0zJXEsgBpjUPHNJLjBNWl0g66
        5wHXv28H+aeeNfWjL+r3AAAADHJvb3RAcmFuY2hlcgE=
        -----END OPENSSH PRIVATE KEY-----
      ed25519-pub: |+
        ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJXEsgBpjUPHNJLjBNWl0g665wHXv28H+aeeNfWjL+r3 root@rancher
      rsa: |+
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
        NhAAAAAwEAAQAAAQEAzNpHfQ3q3MItCThehngAzhkRGXqzWAZYwfwqni8EdcuGoeYRSfO5
        z6WGLhyenkp6ajt/jN4EHnkeUn853vzjdcDY1BgS1/qfX3wPic0mOwJ4jNTle6Aa9He9tQ
        DZc7C9DQ919SbcKs1VJW7kUB1lwVz93DwxNU1x0ia4WLzx1vhnnPFMkaBaX5x9AsjUDwb1
        1HDyk01jVr7iKatfa+uqo2X0FNywNBGM72InSr7TFQKvyxOR8Keh8qZQU4fjzjqaK/V8Xj
        nqao3NkxMUbbtI/qOnll/6kmJmjEDppX8Nk4nxpsKaVhVbDErFQ6A2p+rrAzokW46u8LYD
        pmQloZGVMQAAA8jzsOAR87DgEQAAAAdzc2gtcnNhAAABAQDM2kd9Dercwi0JOF6GeADOGR
        EZerNYBljB/CqeLwR1y4ah5hFJ87nPpYYuHJ6eSnpqO3+M3gQeeR5Sfzne/ON1wNjUGBLX
        +p9ffA+JzSY7AniM1OV7oBr0d721ANlzsL0ND3X1JtwqzVUlbuRQHWXBXP3cPDE1TXHSJr
        hYvPHW+Gec8UyRoFpfnH0CyNQPBvXUcPKTTWNWvuIpq19r66qjZfQU3LA0EYzvYidKvtMV
        Aq/LE5Hwp6HyplBTh+POOpor9XxeOepqjc2TExRtu0j+o6eWX/qSYmaMQOmlfw2TifGmwp
        pWFVsMSsVDoDan6usDOiRbjq7wtgOmZCWhkZUxAAAAAwEAAQAAAQAXb9nB+vel7ilM5sAZ
        zlz5N3D3Y0xlg8Rf3UPa+TIfb/ulRjcwKMxXb26ck/Wp0oeS49/B9Bywh9bqRVgPpQs5C6
        lDCsYNI8VcHUuBzpDTK4MzSaA/tp+e3Jw9uy0lyVC3z88FDz8dPoTBVaCVceeUadk5e0F+
        AbBGBNwOev+IQorfJZcRhJhP1pwtVlJEP97XrvdeO4L2ep6sJ/JJazeoZUwCDaeHaoEGhP
        vIQ5vXilcF5KQuVFB2PyPqTYb0MGQFjRFtsIN8y/4reNjZTH52jW1iws/CPns7XsAbVgg/
        ExWE1xjmiNo1zonDhROnrFFuX7ZLa0+YjXdlrO1lIkqJAAAAgQDMn51SpsCy4Jk5Nnj+bX
        G1qJk/RrB5BU40eFpnr1SWF0G1+1bIB+H31f5hLPxWWlspR5oZY7oxUy1ARl9vz/8saN5h
        XG1gpPEzxY7pewuU5cdZPudJv7tcDVl5YfuRicHifDkvTd2A9/1004x+R6V9KJ7IqOT0Cl
        uGCE4UNGtD6wAAAIEA6XQ48/2sAvKwiaFHdaRIYGt8z5fkHtzYpypHQgSLKJpVTBnYGBmI
        UzGMEZXw3PeJP0fvl7Wwir4I0UFMUnsqrLjKEcQduTnBr4MocNjnYCm1/SKilx1XvCubmN
        s3wWj8iDqC26Zy6la49R0HWczAyZa8h4z9noXetCabf3M1WlMAAACBAOCi7yvhvg+TMrF8
        3t1FUdY6QNpatPRg2mC7kCS7YmIXX057Mz86fgMCqsgpC9LowJK3DGqpkd2NzxDPZpzOVr
        tUrWW6V7JFx03yuWUHBcP9j8a3MtIcZlJdBvsW9SpCVqCIBRjVrXocLRuJCQPAvT8sIJXw
        lgOnGa9mgd6VEknrAAAADHJvb3RAcmFuY2hlcgECAwQFBg==
        -----END OPENSSH PRIVATE KEY-----
      rsa-pub: |+
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDM2kd9Dercwi0JOF6GeADOGREZerNYBljB/CqeLwR1y4ah5hFJ87nPpYYuHJ6eSnpqO3+M3gQeeR5Sfzne/ON1wNjUGBLX+p9ffA+JzSY7AniM1OV7oBr0d721ANlzsL0ND3X1JtwqzVUlbuRQHWXBXP3cPDE1TXHSJrhYvPHW+Gec8UyRoFpfnH0CyNQPBvXUcPKTTWNWvuIpq19r66qjZfQU3LA0EYzvYidKvtMVAq/LE5Hwp6HyplBTh+POOpor9XxeOepqjc2TExRtu0j+o6eWX/qSYmaMQOmlfw2TifGmwppWFVsMSsVDoDan6usDOiRbjq7wtgOmZCWhkZUx root@rancher
  state:
    autoformat:
    - /dev/sda
    dev: LABEL=B2D_STATE
